name: Discord PR Notification

on:
  workflow_call:
    inputs:
      pr_title:
        description: 'PR title'
        type: string
        required: true
      pr_number:
        description: 'PR number'
        type: string
        required: true
      pr_url:
        description: 'PR URL'
        type: string
        required: true
      repo_full_name:
        description: 'Repo full name'
        type: string
        required: true
      pr_draft:
        description: 'PR draft status'
        type: boolean
        required: true
    secrets:
      discord_webhook:
        description: 'Discord webhook URL'
        required: true


jobs:
  notify_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR notification to Discord
        env:
          PR_TITLE: ${{ inputs.pr_title }}
          PR_NUMBER: ${{ inputs.pr_number }}
          PR_URL: ${{ inputs.pr_url }}
          REPO_FULL_NAME: ${{ inputs.repo_full_name }}
          PR_DRAFT: ${{ inputs.pr_draft }}
          DISCORD_WEBHOOK: ${{ secrets.discord_webhook }}
        run: |
          # Determine the message based on the event type and draft status
          if [[ "${{ github.event.action }}" == "opened" ]]; then
            if [[ "$PR_DRAFT" == "true" ]]; then
              ACTION_ICON="📝"
              ACTION_TEXT="draft has been opened."
            else
              ACTION_ICON="<:devpropened:1275356590316322858>"
              ACTION_TEXT="has been opened. Please review!"
            fi
          elif [[ "${{ github.event.action }}" == "ready_for_review" ]]; then
            ACTION_ICON="<:devpropened:1275356590316322858>"
            ACTION_TEXT="is ready for review!"
          elif [[ "${{ github.event.action }}" == "converted_to_draft" ]]; then
            ACTION_ICON="📝"
            ACTION_TEXT="has been converted to draft."
          elif [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            ACTION_ICON="<:devprmerged:1275356589284393021>"
            ACTION_TEXT="has been merged!"
          elif [[ "${{ github.event.action }}" == "closed" ]]; then
            ACTION_ICON="<:devprclosed:1275356586218356776>"
            ACTION_TEXT="has been closed!"
          else
            echo "Unhandled event type. Exiting."
            exit 0
          fi

          REPO_NAME=$(echo $REPO_FULL_NAME | cut -d'/' -f2)
          MESSAGE=$(jq -n \
            --arg repo "$REPO_NAME" \
            --arg number "$PR_NUMBER" \
            --arg title "$PR_TITLE" \
            --arg url "$PR_URL" \
            --arg icon "$ACTION_ICON" \
            --arg action "$ACTION_TEXT" \
            '{content: "\($icon) \($repo) > [PR #\($number): \($title)](\($url)) \($action)"}')

          # Send the notification to Discord
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "$MESSAGE" \
            "$DISCORD_WEBHOOK"
